version: '3.3'

services:

  backend:
    container_name: DeepTSF-backend
    hostname: DeepTSF-backend
    #image: pelekhs/load-forecasting-pipeline:0.1
    build: .
    restart: always
    ports:
      - '8086:8080'
    expose:
      - '8086'
    stdin_open: true
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    networks:
       - load-forecasting-net

#   frontend:
#     container_name: load-forecasting-dashboard
#     hostname: load-forecasting-dashboard
#     image: load-forecasting-dashboard:0.1
#     restart: always
#     # build: /new_vol_300/opt/load-forecasting-dashboard/
#     # build: ./load-forecasting-dashboard
#       # context: ""
#     # volumes:
#     #   # - ./load-forecasting-dashboard/src:/app/src
#     # - /new_vol_300/opt/load-forecasting-dashboard/src:/app/src
#     ports:
#       - '3000:3000'
#     stdin_open: true
#     # environment:
#     #   - CHOKIDAR_USEPOLLING=true
#     #   - REACT_APP_NAME=Load_Forecasting_Dashboard
#     env_file:
#       - .env
#     networks:
#       - load-forecasting-net

networks: 
  load-forecasting-net:
    name: load-forecasting-net
    external: true
