version: '3.8'

services:
  darts-dagster:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./dagster-deeptsf:/app/dagster  # Mount a local volume into the container
      - ./uc2:/app/uc2
      - ./utils.py:/app/utils.py
    networks:
      - load-forecasting-net


networks:
  load-forecasting-net:
    external: true