version: '3.3'
# to run this you need to create a .env file with the contents of .env_keycloak and fill the missing variables.
services:

  backend:
    container_name: DeepTSF-backend
    hostname: DeepTSF-backend
    #image: pelekhs/load-forecasting-pipeline:0.1
    build:
      context: .
      dockerfile: ./Dockerfile_keycloak
    restart: always
    ports:
      - '8080:8080'
    expose:
      - 8080
    stdin_open: true
    # deploy: # use this configuration for GPU usage (if GPU available)
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    env_file:
      - .env
    networks:
       - inergy_network

  dagster:
    container_name: DeepTSF--dagster-orchestrator
    hostname: DeepTSF--dagster-orchestrator
    build:
      context: .
      dockerfile: ./dagster-deeptsf/config/Dockerfile
    env_file:
      - .env
    # environment:
    #   MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
    #   MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
    #   AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    #   AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    expose:
      - 8006
    # ports:
    #   - "8006:8006"
    volumes:
      - dagster-logs:/app/dagster-deeptsf
#      - ./uc2:/app/uc2
    networks:
       - inergy_network

  # frontend:
  #   container_name: load-forecasting-dashboard
  #   hostname: load-forecasting-dashboard
  #   # image: korbakis/load-forecasting-dashboard:0.1
  #   restart: always
  #   # build: ./load-forecasting-dashboard
  #   build: https://github.com/I-NERGY/DeepTSF.git
  #   # volumes: # this bind mount is maybe redundant?
  #   #   - ./src:/app/src # check if this works like that. relative paths are inside the build directory or the current directory?
  #   ports:
  #     - '3000:3000'
  #   stdin_open: true
  #   env_file:
  #     - .env # needs to add all variables of the front-end env_file to the current .env
  #   # environment:
  #   #   CHOKIDAR_USEPOLLING: true
  #   #   REACT_APP_NAME: Load_Forecasting_Dashboard
  #   networks:
  #     - load-forecasting-net

volumes:
    dagster-logs: 

networks:
  inergy_network:
    external: true