name: rdn
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  # - python==3.9.0
  # - pip
  # - pip:
  #     mlflow==1.13.1
  #     sklearn==0.24.1
  #     lightgbm==3.1.1
  #     pandas==1.2.0
  #     numpy==1.19.5
  #     click==7.1.2